StylesPath = .ci/styles
Vocab = SimplePixelFont
Packages = Google, write-good, proselint

# Ignore everything inside the internal styles directory completely
[.ci/styles/**]
BasedOnStyles =

[*.md]
BasedOnStyles = Vale, Google, write-good, proselint
