StylesPath = .ci/styles
Vocab = SimplePixelFont
Packages = Google, write-good, proselint

# Tell Vale to ignore everything in the .ci directory
[*]
BlockIgnores = (?s)(.ci/.*)

[*.md]
BasedOnStyles = Vale, Google, write-good, proselint
