name: Sync Documentation to Wiki

on:
  push:
    branches:
      - main
      - documentation

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Process markdown files
        run: npx https://github.com/The-Nice-One/rail-yard.git preprocess -i ./src -o ./build
      
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          branch: main
          source: build
          destination: wiki
          token: ${{ secrets.TOKEN }}